[0m23:30:02.023563 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fe22c64da80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fe22aaa2e30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fe22aaa1750>]}


============================== 23:30:02.033635 | ca33bc75-e44b-40fb-bc2a-f5d05cbda7af ==============================
[0m23:30:02.033635 [info ] [MainThread]: Running with dbt=1.7.4
[0m23:30:02.034076 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': '/home/timoguin/dev/tiki/data-consumer-use-cases/examples/local_delivery_service/logs', 'profiles_dir': '/home/timoguin/dev/tiki/data-consumer-use-cases/examples/local_delivery_service', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt compile', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m23:30:02.036090 [error] [MainThread]: Encountered an error:
Runtime Error
  
  dbt encountered an error while trying to read your profiles.yml file.
  
  Runtime Error
    Syntax error near line 6
    ------------------------------
    3  |     dev:
    4  |       type: athena
    5  |       threads: 8
    6  |       aws_profile_name: {{ var("aws_profile") }}
    7  |       region_name: {{ var("athena_region") }}
    8  |       schema: {{ var("database_name") }}
    9  |       workgroup: {{ var("athena_workgroup") }}
    
    Raw Error:
    ------------------------------
    while constructing a mapping
      in "<unicode string>", line 6, column 25
    found unhashable key
      in "<unicode string>", line 6, column 26
  
[0m23:30:02.036853 [debug] [MainThread]: Resource report: {"command_name": "compile", "command_wall_clock_time": 0.015617087, "process_user_time": 2.312008, "process_kernel_time": 0.240208, "process_mem_max_rss": "99492", "process_out_blocks": "25496", "command_success": false, "process_in_blocks": "0"}
[0m23:30:02.037278 [debug] [MainThread]: Command `dbt compile` failed at 23:30:02.037172 after 0.02 seconds
[0m23:30:02.037534 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fe22c64da80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fe22a936b60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fe22a937340>]}
[0m23:30:02.037802 [debug] [MainThread]: Flushing usage events
[0m23:49:38.904654 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f0c1be9ec80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f0c1e0be320>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f0c1a1513c0>]}


============================== 23:49:38.906660 | 40eb84cf-3d10-457f-a19f-4a5bf9b709a6 ==============================
[0m23:49:38.906660 [info ] [MainThread]: Running with dbt=1.7.4
[0m23:49:38.907067 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': '/home/timoguin/dev/tiki/data-consumer-use-cases/examples/local_delivery_service', 'log_path': '/home/timoguin/dev/tiki/data-consumer-use-cases/examples/local_delivery_service/logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt compile --vars {database_name:cr_default,athena_region:us-east-2,athena_workgroup:primary,athena_s3_staging_dir:s3://athena-query-results-767398138063-us-east-2/,aws_profile:tiki-sandbox-timoguin.Developer}', 'send_anonymous_usage_stats': 'True'}
[0m23:49:38.909037 [error] [MainThread]: Encountered an error:
Runtime Error
  
  dbt encountered an error while trying to read your profiles.yml file.
  
  Runtime Error
    Syntax error near line 6
    ------------------------------
    3  |     dev:
    4  |       type: athena
    5  |       threads: 8
    6  |       aws_profile_name: {{ var("aws_profile") }}
    7  |       region_name: {{ var("athena_region") }}
    8  |       schema: {{ var("database_name") }}
    9  |       workgroup: {{ var("athena_workgroup") }}
    
    Raw Error:
    ------------------------------
    while constructing a mapping
      in "<unicode string>", line 6, column 25
    found unhashable key
      in "<unicode string>", line 6, column 26
  
[0m23:49:38.909685 [debug] [MainThread]: Resource report: {"command_name": "compile", "command_wall_clock_time": 0.007052904, "process_user_time": 1.453072, "process_kernel_time": 0.049762, "process_mem_max_rss": "91164", "process_out_blocks": "16", "command_success": false, "process_in_blocks": "0"}
[0m23:49:38.910143 [debug] [MainThread]: Command `dbt compile` failed at 23:49:38.910032 after 0.01 seconds
[0m23:49:38.910400 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f0c1be9ec80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f0c1a152620>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f0c1a1523b0>]}
[0m23:49:38.910705 [debug] [MainThread]: Flushing usage events
[0m23:50:50.137581 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb5e8ed6c80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb5eb096320>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb5e719d3c0>]}


============================== 23:50:50.139609 | 2fa518c5-ece2-4a74-96dd-26a5c7afd512 ==============================
[0m23:50:50.139609 [info ] [MainThread]: Running with dbt=1.7.4
[0m23:50:50.148504 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/timoguin/dev/tiki/data-consumer-use-cases/examples/local_delivery_service', 'version_check': 'True', 'warn_error': 'None', 'log_path': '/home/timoguin/dev/tiki/data-consumer-use-cases/examples/local_delivery_service/logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'invocation_command': 'dbt compile --vars {"database_name":"cr_default","athena_region":"us-east-2","athena_workgroup":"primary","athena_s3_staging_dir":"s3://athena-query-results-767398138063-us-east-2/","aws_profile":"tiki-sandbox-timoguin.Developer"}', 'send_anonymous_usage_stats': 'True'}
[0m23:50:50.150647 [error] [MainThread]: Encountered an error:
Runtime Error
  
  dbt encountered an error while trying to read your profiles.yml file.
  
  Runtime Error
    Syntax error near line 6
    ------------------------------
    3  |     dev:
    4  |       type: athena
    5  |       threads: 8
    6  |       aws_profile_name: {{ var("aws_profile") }}
    7  |       region_name: {{ var("athena_region") }}
    8  |       schema: {{ var("database_name") }}
    9  |       workgroup: {{ var("athena_workgroup") }}
    
    Raw Error:
    ------------------------------
    while constructing a mapping
      in "<unicode string>", line 6, column 25
    found unhashable key
      in "<unicode string>", line 6, column 26
  
[0m23:50:50.151312 [debug] [MainThread]: Resource report: {"command_name": "compile", "command_wall_clock_time": 0.01580407, "process_user_time": 1.438639, "process_kernel_time": 0.059529, "process_mem_max_rss": "91280", "process_out_blocks": "16", "command_success": false, "process_in_blocks": "0"}
[0m23:50:50.151717 [debug] [MainThread]: Command `dbt compile` failed at 23:50:50.151612 after 0.02 seconds
[0m23:50:50.151972 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb5e8ed6c80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb5e719e620>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb5e719e3b0>]}
[0m23:50:50.152243 [debug] [MainThread]: Flushing usage events
[0m23:54:09.615809 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f0af684b640>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f0af4ac7dc0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f0af4ac7ee0>]}


============================== 23:54:09.617587 | 070c5f94-badd-4555-98b0-7dcf56e756b5 ==============================
[0m23:54:09.617587 [info ] [MainThread]: Running with dbt=1.7.4
[0m23:54:09.617986 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/timoguin/dev/tiki/data-consumer-use-cases/examples/local_delivery_service', 'debug': 'False', 'warn_error': 'None', 'log_path': '/home/timoguin/dev/tiki/data-consumer-use-cases/examples/local_delivery_service/logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt compile --vars {"aws_profile":"foo"}', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m23:54:09.619876 [error] [MainThread]: Encountered an error:
Runtime Error
  
  dbt encountered an error while trying to read your profiles.yml file.
  
  Runtime Error
    Syntax error near line 6
    ------------------------------
    3  |     dev:
    4  |       type: athena
    5  |       threads: 8
    6  |       aws_profile_name: {{ var("aws_profile") }}
    7  |       region_name: {{ var("athena_region") }}
    8  |       schema: {{ var("database_name") }}
    9  |       workgroup: {{ var("athena_workgroup") }}
    
    Raw Error:
    ------------------------------
    while constructing a mapping
      in "<unicode string>", line 6, column 25
    found unhashable key
      in "<unicode string>", line 6, column 26
  
[0m23:54:09.620486 [debug] [MainThread]: Resource report: {"command_name": "compile", "command_wall_clock_time": 0.00674855, "process_user_time": 1.49601, "process_kernel_time": 0.049867, "process_mem_max_rss": "91292", "process_out_blocks": "8", "command_success": false, "process_in_blocks": "0"}
[0m23:54:09.620844 [debug] [MainThread]: Command `dbt compile` failed at 23:54:09.620750 after 0.01 seconds
[0m23:54:09.621132 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f0af684b640>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f0af4afe470>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f0af4afe200>]}
[0m23:54:09.621440 [debug] [MainThread]: Flushing usage events
[0m23:54:28.972806 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fdcef5c7640>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fdced83fdf0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fdced83fee0>]}


============================== 23:54:28.974907 | 318e3f61-6cff-43f0-b299-eb0cafead708 ==============================
[0m23:54:28.974907 [info ] [MainThread]: Running with dbt=1.7.4
[0m23:54:28.975330 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/timoguin/dev/tiki/data-consumer-use-cases/examples/local_delivery_service', 'version_check': 'True', 'debug': 'False', 'log_path': '/home/timoguin/dev/tiki/data-consumer-use-cases/examples/local_delivery_service/logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt compile --vars {aws_profile:foo}', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m23:54:28.977261 [error] [MainThread]: Encountered an error:
Runtime Error
  
  dbt encountered an error while trying to read your profiles.yml file.
  
  Runtime Error
    Syntax error near line 6
    ------------------------------
    3  |     dev:
    4  |       type: athena
    5  |       threads: 8
    6  |       aws_profile_name: {{ var("aws_profile") }}
    7  |       region_name: {{ var("athena_region") }}
    8  |       schema: {{ var("database_name") }}
    9  |       workgroup: {{ var("athena_workgroup") }}
    
    Raw Error:
    ------------------------------
    while constructing a mapping
      in "<unicode string>", line 6, column 25
    found unhashable key
      in "<unicode string>", line 6, column 26
  
[0m23:54:28.977876 [debug] [MainThread]: Resource report: {"command_name": "compile", "command_wall_clock_time": 0.007374058, "process_user_time": 1.491404, "process_kernel_time": 0.020018, "process_mem_max_rss": "91148", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m23:54:28.978253 [debug] [MainThread]: Command `dbt compile` failed at 23:54:28.978153 after 0.01 seconds
[0m23:54:28.978501 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fdcef5c7640>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fdced876410>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fdced8761a0>]}
[0m23:54:28.978761 [debug] [MainThread]: Flushing usage events
[0m23:54:33.275274 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3f67103640>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3f65333ee0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3f65333e50>]}


============================== 23:54:33.277329 | 7e9b74a5-4990-4280-b8f0-39a4f02d9357 ==============================
[0m23:54:33.277329 [info ] [MainThread]: Running with dbt=1.7.4
[0m23:54:33.277802 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': '/home/timoguin/dev/tiki/data-consumer-use-cases/examples/local_delivery_service', 'log_path': '/home/timoguin/dev/tiki/data-consumer-use-cases/examples/local_delivery_service/logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'invocation_command': 'dbt compile --vars {aws_profile: foo}', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m23:54:33.279720 [error] [MainThread]: Encountered an error:
Runtime Error
  
  dbt encountered an error while trying to read your profiles.yml file.
  
  Runtime Error
    Syntax error near line 6
    ------------------------------
    3  |     dev:
    4  |       type: athena
    5  |       threads: 8
    6  |       aws_profile_name: {{ var("aws_profile") }}
    7  |       region_name: {{ var("athena_region") }}
    8  |       schema: {{ var("database_name") }}
    9  |       workgroup: {{ var("athena_workgroup") }}
    
    Raw Error:
    ------------------------------
    while constructing a mapping
      in "<unicode string>", line 6, column 25
    found unhashable key
      in "<unicode string>", line 6, column 26
  
[0m23:54:33.280310 [debug] [MainThread]: Resource report: {"command_name": "compile", "command_wall_clock_time": 0.007045924, "process_user_time": 1.473256, "process_kernel_time": 0.019775, "process_mem_max_rss": "91036", "process_out_blocks": "8", "command_success": false, "process_in_blocks": "0"}
[0m23:54:33.280701 [debug] [MainThread]: Command `dbt compile` failed at 23:54:33.280600 after 0.01 seconds
[0m23:54:33.280947 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3f67103640>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3f6536a500>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3f6536a290>]}
[0m23:54:33.281202 [debug] [MainThread]: Flushing usage events
[0m23:55:11.925900 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f6584707520>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f6582b3bdf0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f6582b3bee0>]}


============================== 23:55:11.927703 | e6f8a128-923c-4e77-aabd-9a75df671953 ==============================
[0m23:55:11.927703 [info ] [MainThread]: Running with dbt=1.7.4
[0m23:55:11.928091 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': '/home/timoguin/dev/tiki/data-consumer-use-cases/examples/local_delivery_service', 'log_path': '/home/timoguin/dev/tiki/data-consumer-use-cases/examples/local_delivery_service/logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt compile --vars aws_profile: foo', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m23:55:11.929984 [error] [MainThread]: Encountered an error:
Runtime Error
  
  dbt encountered an error while trying to read your profiles.yml file.
  
  Runtime Error
    Syntax error near line 6
    ------------------------------
    3  |     dev:
    4  |       type: athena
    5  |       threads: 8
    6  |       aws_profile_name: {{ var("aws_profile") }}
    7  |       region_name: {{ var("athena_region") }}
    8  |       schema: {{ var("database_name") }}
    9  |       workgroup: {{ var("athena_workgroup") }}
    
    Raw Error:
    ------------------------------
    while constructing a mapping
      in "<unicode string>", line 6, column 25
    found unhashable key
      in "<unicode string>", line 6, column 26
  
[0m23:55:11.930580 [debug] [MainThread]: Resource report: {"command_name": "compile", "command_wall_clock_time": 0.006696299, "process_user_time": 1.42555, "process_kernel_time": 0.049498, "process_mem_max_rss": "91128", "process_out_blocks": "16", "command_success": false, "process_in_blocks": "0"}
[0m23:55:11.930934 [debug] [MainThread]: Command `dbt compile` failed at 23:55:11.930842 after 0.01 seconds
[0m23:55:11.931175 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f6584707520>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f6582b72350>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f6582b720e0>]}
[0m23:55:11.931429 [debug] [MainThread]: Flushing usage events
[0m23:56:03.390214 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3d389fb640>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3d36c73ee0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3d36c73e80>]}


============================== 23:56:03.392136 | 35632e72-56b3-4cc6-9736-f46c8235d375 ==============================
[0m23:56:03.392136 [info ] [MainThread]: Running with dbt=1.7.4
[0m23:56:03.392568 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': '/home/timoguin/dev/tiki/data-consumer-use-cases/examples/local_delivery_service/logs', 'debug': 'False', 'profiles_dir': '/home/timoguin/dev/tiki/data-consumer-use-cases/examples/local_delivery_service', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt compile --vars {aws_profile: foo, athena_region: bar, database_name: dadata, athena_workgroup: yayaya}', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m23:56:03.394444 [error] [MainThread]: Encountered an error:
Runtime Error
  
  dbt encountered an error while trying to read your profiles.yml file.
  
  Runtime Error
    Syntax error near line 6
    ------------------------------
    3  |     dev:
    4  |       type: athena
    5  |       threads: 8
    6  |       aws_profile_name: {{ var("aws_profile") }}
    7  |       region_name: {{ var("athena_region") }}
    8  |       schema: {{ var("database_name") }}
    9  |       workgroup: {{ var("athena_workgroup") }}
    
    Raw Error:
    ------------------------------
    while constructing a mapping
      in "<unicode string>", line 6, column 25
    found unhashable key
      in "<unicode string>", line 6, column 26
  
[0m23:56:03.395042 [debug] [MainThread]: Resource report: {"command_name": "compile", "command_wall_clock_time": 0.006951217, "process_user_time": 1.418423, "process_kernel_time": 0.069922, "process_mem_max_rss": "91380", "process_out_blocks": "8", "command_success": false, "process_in_blocks": "0"}
[0m23:56:03.395499 [debug] [MainThread]: Command `dbt compile` failed at 23:56:03.395344 after 0.01 seconds
[0m23:56:03.395786 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3d389fb640>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3d36caa4a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3d36caa230>]}
[0m23:56:03.396060 [debug] [MainThread]: Flushing usage events
[0m23:57:12.401844 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb99623f640>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb994382020>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb994381fc0>]}


============================== 23:57:12.403668 | 43511325-f466-46bb-829d-0d09323da5e0 ==============================
[0m23:57:12.403668 [info ] [MainThread]: Running with dbt=1.7.4
[0m23:57:12.404069 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/timoguin/dev/tiki/data-consumer-use-cases/examples/local_delivery_service', 'debug': 'False', 'fail_fast': 'False', 'log_path': '/home/timoguin/dev/tiki/data-consumer-use-cases/examples/local_delivery_service/logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt compile --vars {aws_profile: foo, athena_region: bar, database_name: dadata, athena_workgroup: yayaya}', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m23:57:12.405801 [error] [MainThread]: Encountered an error:
Runtime Error
  Could not find profile named 'tiki_cr'
[0m23:57:12.406388 [debug] [MainThread]: Resource report: {"command_name": "compile", "command_wall_clock_time": 0.03522231, "process_user_time": 1.472792, "process_kernel_time": 0.050438, "process_mem_max_rss": "91764", "process_out_blocks": "8", "command_success": false, "process_in_blocks": "0"}
[0m23:57:12.406775 [debug] [MainThread]: Command `dbt compile` failed at 23:57:12.406677 after 0.04 seconds
[0m23:57:12.407025 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb99623f640>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb994383250>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb994383a60>]}
[0m23:57:12.407280 [debug] [MainThread]: Flushing usage events
[0m23:57:32.091338 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f97c7df2c80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f97c5ef2170>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f97c5ef2110>]}


============================== 23:57:32.093297 | c75ecf42-6b3a-4aeb-8a5f-c2bb48d4d86b ==============================
[0m23:57:32.093297 [info ] [MainThread]: Running with dbt=1.7.4
[0m23:57:32.093714 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/timoguin/dev/tiki/data-consumer-use-cases/examples/local_delivery_service', 'version_check': 'True', 'debug': 'False', 'log_path': '/home/timoguin/dev/tiki/data-consumer-use-cases/examples/local_delivery_service/logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt compile --vars {"database_name":"cr_default","athena_region":"us-east-2","athena_workgroup":"primary","athena_s3_staging_dir":"s3://athena-query-results-767398138063-us-east-2/","aws_profile":"tiki-sandbox-timoguin.Developer"}', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m23:57:32.095529 [error] [MainThread]: Encountered an error:
Runtime Error
  Could not find profile named 'tiki_cr'
[0m23:57:32.096169 [debug] [MainThread]: Resource report: {"command_name": "compile", "command_wall_clock_time": 0.03635708, "process_user_time": 1.477927, "process_kernel_time": 0.069901, "process_mem_max_rss": "91920", "process_out_blocks": "8", "command_success": false, "process_in_blocks": "0"}
[0m23:57:32.096586 [debug] [MainThread]: Command `dbt compile` failed at 23:57:32.096484 after 0.04 seconds
[0m23:57:32.096862 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f97c7df2c80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f97c5ef33a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f97c5ef3a60>]}
[0m23:57:32.097141 [debug] [MainThread]: Flushing usage events
[0m23:57:57.327487 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fef3c20a290>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fef3a352110>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fef3a3520b0>]}


============================== 23:57:57.329391 | 385e9289-385e-4243-b156-4bc4f95e8768 ==============================
[0m23:57:57.329391 [info ] [MainThread]: Running with dbt=1.7.4
[0m23:57:57.329804 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/timoguin/dev/tiki/data-consumer-use-cases/examples/local_delivery_service', 'fail_fast': 'False', 'debug': 'False', 'log_path': '/home/timoguin/dev/tiki/data-consumer-use-cases/examples/local_delivery_service/logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt compile --vars {"database_name":"cr_default","athena_region":"us-east-2","athena_workgroup":"primary","athena_s3_staging_dir":"s3://athena-query-results-767398138063-us-east-2/","aws_profile":"tiki-sandbox-timoguin.Developer"}', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m23:57:57.330483 [error] [MainThread]: Encountered an error:
Runtime Error
  dbt cannot run because no profile was specified for this dbt project.
  To specify a profile for this project, add a line like the this to
  your dbt_project.yml file:
  
  profile: [profile name]
  
  Here, [profile name] should be replaced with a profile name
  defined in your profiles.yml file. You can find profiles.yml here:
  
  /home/timoguin/dev/tiki/data-consumer-use-cases/examples/local_delivery_service/profiles.yml
  
[0m23:57:57.331082 [debug] [MainThread]: Resource report: {"command_name": "compile", "command_wall_clock_time": 0.034554165, "process_user_time": 1.441211, "process_kernel_time": 0.069575, "process_mem_max_rss": "91752", "process_out_blocks": "8", "command_success": false, "process_in_blocks": "0"}
[0m23:57:57.331534 [debug] [MainThread]: Command `dbt compile` failed at 23:57:57.331426 after 0.04 seconds
[0m23:57:57.331821 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fef3c20a290>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fef3a3523e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fef3a352d40>]}
[0m23:57:57.332107 [debug] [MainThread]: Flushing usage events
[0m23:58:22.088017 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f1532fba260>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f15311020e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f1531102080>]}


============================== 23:58:22.090120 | 0ed6b5c2-e306-4109-ae8c-1625ef09c7c2 ==============================
[0m23:58:22.090120 [info ] [MainThread]: Running with dbt=1.7.4
[0m23:58:22.090538 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/timoguin/dev/tiki/data-consumer-use-cases/examples/local_delivery_service', 'debug': 'False', 'version_check': 'True', 'log_path': '/home/timoguin/dev/tiki/data-consumer-use-cases/examples/local_delivery_service/logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt compile --vars {"database_name":"cr_default","athena_region":"us-east-2","athena_workgroup":"primary","athena_s3_staging_dir":"s3://athena-query-results-767398138063-us-east-2/","aws_profile":"tiki-sandbox-timoguin.Developer"}', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m23:58:22.511911 [error] [MainThread]: Encountered an error:
Runtime Error
  Credentials in profile "athena", target "dev" invalid: 'database' is a required property
[0m23:58:22.512661 [debug] [MainThread]: Resource report: {"command_name": "compile", "command_wall_clock_time": 0.45507467, "process_user_time": 1.847333, "process_kernel_time": 0.08987, "process_mem_max_rss": "119360", "process_out_blocks": "5752", "command_success": false, "process_in_blocks": "0"}
[0m23:58:22.513089 [debug] [MainThread]: Command `dbt compile` failed at 23:58:22.512984 after 0.46 seconds
[0m23:58:22.513382 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f1532fba260>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f1531102d40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f15308146a0>]}
[0m23:58:22.513679 [debug] [MainThread]: Flushing usage events
[0m00:01:08.736178 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f6855e06290>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f6853f4a110>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f6853f4a0b0>]}


============================== 00:01:08.738079 | 3a1239ed-4180-47c9-b1bc-143b0df1d6db ==============================
[0m00:01:08.738079 [info ] [MainThread]: Running with dbt=1.7.4
[0m00:01:08.738496 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/timoguin/dev/tiki/data-consumer-use-cases/examples/local_delivery_service', 'version_check': 'True', 'fail_fast': 'False', 'log_path': '/home/timoguin/dev/tiki/data-consumer-use-cases/examples/local_delivery_service/logs', 'warn_error': 'None', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt compile --vars {"athena_database":"awsdatacatalog","athena_schema":"cr_default","athena_region":"us-east-2","athena_workgroup":"primary","athena_s3_staging_dir":"s3://athena-query-results-767398138063-us-east-2/","aws_profile":"tiki-sandbox-timoguin.Developer"}', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m00:01:09.008574 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': '3a1239ed-4180-47c9-b1bc-143b0df1d6db', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f6853f4a200>]}
[0m00:01:09.072360 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': '3a1239ed-4180-47c9-b1bc-143b0df1d6db', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f6852ea9cc0>]}
[0m00:01:09.073128 [info ] [MainThread]: Registered adapter: athena=1.7.1
[0m00:01:09.079277 [debug] [MainThread]: checksum: 2dd2110b0de3803482794ba1bcedbdb01421373d979b2e0bd734319b05a63d8b, vars: {'athena_database': 'awsdatacatalog',
 'athena_region': 'us-east-2',
 'athena_s3_staging_dir': 's3://athena-query-results-767398138063-us-east-2/',
 'athena_schema': 'cr_default',
 'athena_workgroup': 'primary',
 'aws_profile': 'tiki-sandbox-timoguin.Developer'}, profile: , target: , version: 1.7.4
[0m00:01:09.079716 [info ] [MainThread]: Unable to do partial parsing because saved manifest not found. Starting full parse.
[0m00:01:09.080026 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'partial_parser', 'label': '3a1239ed-4180-47c9-b1bc-143b0df1d6db', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f6852ea9d20>]}
[0m00:01:09.778985 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'load_project', 'label': '3a1239ed-4180-47c9-b1bc-143b0df1d6db', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f6852113910>]}
[0m00:01:09.784100 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': '3a1239ed-4180-47c9-b1bc-143b0df1d6db', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f68521379a0>]}
[0m00:01:09.784461 [info ] [MainThread]: Found 1 model, 0 sources, 0 exposures, 0 metrics, 423 macros, 0 groups, 0 semantic models
[0m00:01:09.784773 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': '3a1239ed-4180-47c9-b1bc-143b0df1d6db', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f6852e72fe0>]}
[0m00:01:09.785749 [info ] [MainThread]: 
[0m00:01:09.786332 [debug] [MainThread]: Acquiring new athena connection 'master'
[0m00:01:09.787496 [debug] [ThreadPool]: Acquiring new athena connection 'list_awsdatacatalog_cr_default'
[0m00:01:09.787817 [debug] [ThreadPool]: Opening a new connection, currently in state init
[0m00:01:11.280871 [debug] [ThreadPool]: On list_awsdatacatalog_cr_default: Close
[0m00:01:11.283698 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': '3a1239ed-4180-47c9-b1bc-143b0df1d6db', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f68521051e0>]}
[0m00:01:11.285027 [info ] [MainThread]: Concurrency: 8 threads (target='dev')
[0m00:01:11.285762 [info ] [MainThread]: 
[0m00:01:11.294118 [debug] [Thread-1 (]: Began running node model.local_delivery_service.transactions_pfd
[0m00:01:11.295342 [debug] [Thread-1 (]: Re-using an available connection from the pool (formerly list_awsdatacatalog_cr_default, now model.local_delivery_service.transactions_pfd)
[0m00:01:11.296068 [debug] [Thread-1 (]: Began compiling node model.local_delivery_service.transactions_pfd
[0m00:01:11.304809 [debug] [Thread-1 (]: Writing injected SQL for node "model.local_delivery_service.transactions_pfd"
[0m00:01:11.305830 [debug] [Thread-1 (]: Timing info for model.local_delivery_service.transactions_pfd (compile): 00:01:11.296527 => 00:01:11.305559
[0m00:01:11.306186 [debug] [Thread-1 (]: Began executing node model.local_delivery_service.transactions_pfd
[0m00:01:11.306532 [debug] [Thread-1 (]: Timing info for model.local_delivery_service.transactions_pfd (execute): 00:01:11.306368 => 00:01:11.306380
[0m00:01:11.307233 [debug] [Thread-1 (]: Finished running node model.local_delivery_service.transactions_pfd
[0m00:01:11.309385 [debug] [MainThread]: Connection 'master' was properly closed.
[0m00:01:11.309684 [debug] [MainThread]: Connection 'model.local_delivery_service.transactions_pfd' was properly closed.
[0m00:01:11.310143 [debug] [MainThread]: Command end result
[0m00:01:11.315576 [debug] [MainThread]: Resource report: {"command_name": "compile", "command_success": true, "command_wall_clock_time": 2.6106699, "process_user_time": 2.854902, "process_kernel_time": 0.121055, "process_mem_max_rss": "144348", "process_out_blocks": "2680", "process_in_blocks": "0"}
[0m00:01:11.316024 [debug] [MainThread]: Command `dbt compile` succeeded at 00:01:11.315913 after 2.61 seconds
[0m00:01:11.316318 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f6855e06290>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f6852dec2e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f6852ea9cc0>]}
[0m00:01:11.316620 [debug] [MainThread]: Flushing usage events
[0m00:15:36.659611 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3671c7ecb0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f366fd6a1a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f366fd6a140>]}


============================== 00:15:36.661863 | 90b18edb-1729-43bf-b6c4-26f0f8edf9a7 ==============================
[0m00:15:36.661863 [info ] [MainThread]: Running with dbt=1.7.4
[0m00:15:36.662330 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/timoguin/dev/tiki/data-consumer-use-cases/examples/local_delivery_service', 'version_check': 'True', 'fail_fast': 'False', 'log_path': '/home/timoguin/dev/tiki/data-consumer-use-cases/examples/local_delivery_service/logs', 'warn_error': 'None', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'invocation_command': 'dbt compile --vars {"athena_database":"awsdatacatalog","athena_schema":"cr_default","athena_region":"us-east-2","athena_workgroup":"primary","athena_s3_staging_dir":"s3://athena-query-results-767398138063-us-east-2/","aws_profile":"tiki-sandbox-timoguin.Developer"}', 'send_anonymous_usage_stats': 'True'}
[0m00:15:36.927667 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': '90b18edb-1729-43bf-b6c4-26f0f8edf9a7', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f366fd6a290>]}
[0m00:15:36.992271 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': '90b18edb-1729-43bf-b6c4-26f0f8edf9a7', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f366ff22080>]}
[0m00:15:36.992892 [info ] [MainThread]: Registered adapter: athena=1.7.1
[0m00:15:36.999034 [debug] [MainThread]: checksum: 2dd2110b0de3803482794ba1bcedbdb01421373d979b2e0bd734319b05a63d8b, vars: {'athena_database': 'awsdatacatalog',
 'athena_region': 'us-east-2',
 'athena_s3_staging_dir': 's3://athena-query-results-767398138063-us-east-2/',
 'athena_schema': 'cr_default',
 'athena_workgroup': 'primary',
 'aws_profile': 'tiki-sandbox-timoguin.Developer'}, profile: , target: , version: 1.7.4
[0m00:15:37.013333 [debug] [MainThread]: Partial parsing enabled: 0 files deleted, 0 files added, 0 files changed.
[0m00:15:37.013622 [debug] [MainThread]: Partial parsing enabled, no changes found, skipping parsing
[0m00:15:37.017042 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'load_project', 'label': '90b18edb-1729-43bf-b6c4-26f0f8edf9a7', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f366eaa26b0>]}
[0m00:15:37.021941 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': '90b18edb-1729-43bf-b6c4-26f0f8edf9a7', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f366ea7cd90>]}
[0m00:15:37.022312 [info ] [MainThread]: Found 1 model, 0 sources, 0 exposures, 0 metrics, 423 macros, 0 groups, 0 semantic models
[0m00:15:37.022648 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': '90b18edb-1729-43bf-b6c4-26f0f8edf9a7', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f366ea7cf10>]}
[0m00:15:37.023635 [info ] [MainThread]: 
[0m00:15:37.024221 [debug] [MainThread]: Acquiring new athena connection 'master'
[0m00:15:37.025138 [debug] [ThreadPool]: Acquiring new athena connection 'list_awsdatacatalog_cr_default'
[0m00:15:37.025457 [debug] [ThreadPool]: Opening a new connection, currently in state init
[0m00:15:38.583344 [debug] [ThreadPool]: On list_awsdatacatalog_cr_default: Close
[0m00:15:38.586479 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': '90b18edb-1729-43bf-b6c4-26f0f8edf9a7', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f366ea7cbb0>]}
[0m00:15:38.594823 [info ] [MainThread]: Concurrency: 8 threads (target='dev')
[0m00:15:38.595895 [info ] [MainThread]: 
[0m00:15:38.604652 [debug] [Thread-1 (]: Began running node model.local_delivery_service.transactions_pfd
[0m00:15:38.606092 [debug] [Thread-1 (]: Re-using an available connection from the pool (formerly list_awsdatacatalog_cr_default, now model.local_delivery_service.transactions_pfd)
[0m00:15:38.607007 [debug] [Thread-1 (]: Began compiling node model.local_delivery_service.transactions_pfd
[0m00:15:38.616206 [debug] [Thread-1 (]: Writing injected SQL for node "model.local_delivery_service.transactions_pfd"
[0m00:15:38.616696 [debug] [Thread-1 (]: Timing info for model.local_delivery_service.transactions_pfd (compile): 00:15:38.607526 => 00:15:38.616510
[0m00:15:38.616990 [debug] [Thread-1 (]: Began executing node model.local_delivery_service.transactions_pfd
[0m00:15:38.617327 [debug] [Thread-1 (]: Timing info for model.local_delivery_service.transactions_pfd (execute): 00:15:38.617162 => 00:15:38.617173
[0m00:15:38.617934 [debug] [Thread-1 (]: Finished running node model.local_delivery_service.transactions_pfd
[0m00:15:38.619699 [debug] [MainThread]: Connection 'master' was properly closed.
[0m00:15:38.619970 [debug] [MainThread]: Connection 'model.local_delivery_service.transactions_pfd' was properly closed.
[0m00:15:38.620397 [debug] [MainThread]: Command end result
[0m00:15:38.625659 [debug] [MainThread]: Resource report: {"command_name": "compile", "command_success": true, "command_wall_clock_time": 1.9977442, "process_user_time": 2.170692, "process_kernel_time": 0.070673, "process_mem_max_rss": "140632", "process_out_blocks": "1776", "process_in_blocks": "0"}
[0m00:15:38.626249 [debug] [MainThread]: Command `dbt compile` succeeded at 00:15:38.626104 after 2.00 seconds
[0m00:15:38.626616 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3671c7ecb0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f366ff22080>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f366ea6bb20>]}
[0m00:15:38.626945 [debug] [MainThread]: Flushing usage events
